In [99]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [39]:
df = pd.read_csv("G:/Old pc important files/Downloads/Python/emails.csv")
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [40]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [41]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [42]:
df.isnull().sum()

text    0
spam    0
dtype: int64

Separete x and y

In [69]:
x = df.text.values
y = df.spam.values

Dataset split

In [70]:
from sklearn.model_selection import train_test_split
xtrain ,xtest, ytrain, ytest = train_test_split(x, y, test_size =0.2)

Data Prepcessing

In [81]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [82]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

ML Algroithm

In [73]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [83]:
x_test = cv.transform(xtest)
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [86]:
# make predictions on training data
predictions_train = model.predict(x_train)
print('\nTraining Accuracy :', accuracy_score(ytrain,predictions_train))
# make predictions on test data
predictions_test = model.predict(x_test)
print('\nTest Accuracy :', accuracy_score(ytest, predictions_test))
# model's score
print("\nModel Score :", model.score(x_test,ytest))



Training Accuracy : 0.99628982976866

Test Accuracy : 0.9921465968586387

Model Score : 0.9921465968586387


In [89]:
emails = ['hay i am looking for machine learning tutorials in bengali language','hey you win an iphone x giveaway for free please try get free iPhone X giveaway']

In [90]:
cv_emails = cv.transform(emails)

In [91]:
model.predict(cv_emails)

array([0, 1], dtype=int64)

Performance

In [93]:
pred = model.predict(x_test)

In [94]:
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [95]:
accuracy_score(ytest, pred)

0.9921465968586387

In [98]:
confusion_matrix(ytest, pred)

array([[861,   2],
       [  7, 276]], dtype=int64)

In [100]:
print(classification_report(ytest, pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       863
           1       0.99      0.98      0.98       283

    accuracy                           0.99      1146
   macro avg       0.99      0.99      0.99      1146
weighted avg       0.99      0.99      0.99      1146

