In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv("G:/Old pc important files/Desktop/thesis 2021/dataset/kaggle_parsed_dataset.csv")
df.head()

index  oh_label             Date  \
0      0         1  20120618192155Z   
1      1         0  20120528192215Z   
2      2         0              NaN   
3      3         0              NaN   
4      4         0  20120619094753Z   

                                                Text  
0                               "You fuck your dad."  
1  "i really don't understand your point.\xa0 It ...  
2  "A\\xc2\\xa0majority of Canadians can and has ...  
3  "listen if you dont wanna get married to a man...  
4  "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...

In [5]:
df

index  oh_label             Date  \
0         0         1  20120618192155Z   
1         1         0  20120528192215Z   
2         2         0              NaN   
3         3         0              NaN   
4         4         0  20120619094753Z   
...     ...       ...              ...   
8794   8794         0  20120612003508Z   
8795   8795         0  20120619210456Z   
8796   8796         0  20120528234613Z   
8797   8797         1  20120619153537Z   
8798   8798         0  20120620000237Z   

                                                   Text  
0                                  "You fuck your dad."  
1     "i really don't understand your point.\xa0 It ...  
2     "A\\xc2\\xa0majority of Canadians can and has ...  
3     "listen if you dont wanna get married to a man...  
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...  
...                                                 ...  
8794  "Never really gave it much thought. I just fig...  
8795                 "Nadie se salva de la regla 34 xd"  
8796               "Question: Are you a boy or a girl?"  
8797  "Leave your email or phone number and maybe yo...  
8798  "From the scenarios you present, I see you bel...  

[8799 rows x 4 columns]

In [3]:
df.drop_duplicates(inplace = True)

In [4]:
df

index  oh_label             Date  \
0         0         1  20120618192155Z   
1         1         0  20120528192215Z   
2         2         0              NaN   
3         3         0              NaN   
4         4         0  20120619094753Z   
...     ...       ...              ...   
8794   8794         0  20120612003508Z   
8795   8795         0  20120619210456Z   
8796   8796         0  20120528234613Z   
8797   8797         1  20120619153537Z   
8798   8798         0  20120620000237Z   

                                                   Text  
0                                  "You fuck your dad."  
1     "i really don't understand your point.\xa0 It ...  
2     "A\\xc2\\xa0majority of Canadians can and has ...  
3     "listen if you dont wanna get married to a man...  
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...  
...                                                 ...  
8794  "Never really gave it much thought. I just fig...  
8795                 "Nadie se salva de la regla 34 xd"  
8796               "Question: Are you a boy or a girl?"  
8797  "Leave your email or phone number and maybe yo...  
8798  "From the scenarios you present, I see you bel...  

[8799 rows x 4 columns]

In [6]:
df.isnull().sum()

index          0
oh_label       0
Date        1242
Text           0
dtype: int64

Separete x and y

In [8]:
x = df.Text.values
y = df.oh_label.values

Data Prepcessing

In [25]:
from sklearn.model_selection import train_test_split
xtrain ,xtest, ytrain, ytest = train_test_split(x, y, test_size =0.5)

Data Prepcessing

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [27]:
x_train.toarray()

MemoryError: Unable to allocate 545. MiB for an array with shape (4399, 16239) and data type int64

ML Algroithm

In [28]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [29]:
x_test = cv.transform(xtest)
x_test.toarray()

MemoryError: Unable to allocate 545. MiB for an array with shape (4400, 16239) and data type int64

In [30]:
# make predictions on training data
predictions_train = model.predict(x_train)
print('\nTraining Accuracy :', accuracy_score(ytrain,predictions_train))
# make predictions on test data
predictions_test = model.predict(x_test)
print('\nTest Accuracy :', accuracy_score(ytest, predictions_test))
# model's score
# print("\nModel Score :", model.score(x_test,ytest))


Training Accuracy : 0.9058877017503978

Test Accuracy : 0.7918181818181819


In [32]:
comments = ['hay i am looking for a girl for my office employee','hey your boobs look beautiful']

In [34]:
cv_comments = cv.transform(comments)
model.predict(cv_comments)

array([0, 1], dtype=int64)

Performance

In [35]:
pred = model.predict(x_test)
pred

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [36]:
accuracy_score(ytest, pred)

0.7918181818181819

In [37]:
confusion_matrix(ytest, pred)

array([[2558,  430],
       [ 486,  926]], dtype=int64)

In [38]:
print(classification_report(ytest, pred))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85      2988
           1       0.68      0.66      0.67      1412

    accuracy                           0.79      4400
   macro avg       0.76      0.76      0.76      4400
weighted avg       0.79      0.79      0.79      4400

